"""add recipient to messages

Revision ID: 964f8cf771d8
Revises: 34b71b75873e
Create Date: 2026-08-25 19:41:06.262920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964f8cf771d8'
down_revision: Union[str, Sequence[str], None] = '34b71b75873e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.Integer(), nullable=True))
    
    op.execute(
        "UPDATE messages SET recipient_id = 2 WHERE recipient_id IS NULL"
    )
    op.alter_column(
        "messages",
        "recipient_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    
    op.create_foreign_key(None, 'messages', 'users', ['recipient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'recipient_id')
    # ### end Alembic commands ###
