"""add read_at to messages

Revision ID: dfdc0060d1ed
Revises: 964f8cf771d8
Create Date: 2026-08-31 13:44:34.393803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfdc0060d1ed'
down_revision: Union[str, Sequence[str], None] = '964f8cf771d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('read_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'read_at')
    # ### end Alembic commands ###
